#!/usr/bin/env python3
"""Particle-pressure / bulk-stress test of the Ishizawa breathing residual.

Use the four particle-rich breathing-phase plotfiles generated by
run_ishizawa_scale_particle_phases.sh.  Actual particle velocities are
deposited to a coarse mesh to obtain species pressure moments.

For each species s,

    P_xz = m_s n_s <c_x c_z>
    P_zz = m_s n_s <c_z^2>,

and the vertical pressure-force density is

    f_P,z = -(d_x P_xz + d_z P_zz).

For the affine breathing coordinate delta z = z delta q, the generalized
pressure force is

    Q_P,s = integral z f_P,z dA.

Because x is periodic, the same rectangular-core integral has a much less
noisy virial form

    Q_P,s =
      integral_core P_zz dA
      - [ z integral_x P_zz dx ]_(zlo)^(zhi).

The analogous bulk momentum-flux contribution is

    Q_bulk,s =
      integral_core rho_s u_z^2 dA
      - [ z integral_x rho_s u_z^2 dx ]_(zlo)^(zhi).

These are compared with the non-EM restoring acceleration required by the
field-only diagnostic,

    a_required = a_measured - a_EM.

This four-phase test is deliberately a first mechanism check, not yet a
high-precision harmonic closure.  If pressure/stress tracks the required
residual, a denser particle-rich phase scan is the next step.

Outputs
-------
ishizawa_particle_pressure_phases.txt
ishizawa_particle_pressure_phases_summary.txt
ishizawa_particle_pressure_phases.png
ishizawa_particle_pressure_vs_q.png
"""

import argparse
import glob
import os
import re
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import yt

from analyze_ishizawa_scale_40000 import QE, ME, C, params
from analyze_ishizawa_particle_moments import load_mesh, deposit_species


def parse_args():
    p=argparse.ArgumentParser()
    p.add_argument("--phase-root",default="runs_ishizawa_particle_phases/ppc49")
    p.add_argument("--em-history",required=True,
                   help="ishizawa_generalized_em_force_history.txt")
    p.add_argument("--coarsen",type=int,default=4)
    p.add_argument("--core-z-de",type=float,default=12.0)
    return p.parse_args()


def numeric_key(path):
    m=re.search(r"(\d+)$",os.path.basename(path.rstrip("/")))
    return int(m.group(1)) if m else -1


def step_from_parent(path):
    for part in Path(path).parts[::-1]:
        m=re.fullmatch(r"step(\d+)",part)
        if m:
            return int(m.group(1))
    return numeric_key(path)


def linear_fit(x,y):
    x=np.asarray(x,float); y=np.asarray(y,float)
    m=np.isfinite(x)&np.isfinite(y)
    x=x[m]; y=y[m]
    if len(x)<3:
        return np.nan,np.nan,np.nan
    A=np.column_stack([x,np.ones_like(x)])
    c,*_=np.linalg.lstsq(A,y,rcond=None)
    pred=A@c
    ssr=np.sum((y-pred)**2)
    sst=np.sum((y-np.mean(y))**2)
    r2=1-ssr/sst if sst>0 else np.nan
    return float(c[0]),float(c[1]),float(r2)


def rectangular_virial(Pzz, z, dx, dz, zmax):
    idx=np.where(np.abs(z)<=zmax)[0]
    if len(idx)<3:
        raise RuntimeError("core-z selection contains fewer than 3 cells")
    jlo,jhi=int(idx[0]),int(idx[-1])
    vol=float(np.sum(Pzz[:,jlo:jhi+1])*dx*dz)
    upper=float(z[jhi]*np.sum(Pzz[:,jhi])*dx)
    lower=float(z[jlo]*np.sum(Pzz[:,jlo])*dx)
    # integral Pzz - [z int Pzz dx]_lo^hi
    return vol-upper+lower, jlo, jhi


def direct_pressure_force(Pxz,Pzz,x,z,dx,dz,jlo,jhi):
    dpxz_dx=np.gradient(Pxz,dx,axis=0,edge_order=2)
    dpzz_dz=np.gradient(Pzz,dz,axis=1,edge_order=2)
    fpz=-(dpxz_dx+dpzz_dz)
    Z=np.broadcast_to(z[None,:],Pzz.shape)
    Q=float(np.sum((Z*fpz)[:,jlo:jhi+1])*dx*dz)
    return Q


def main():
    args=parse_args()
    yt.funcs.mylog.setLevel(40)

    P=params()
    p=dict(qe=QE,me=ME,mi=P["mi"],c=C,n0=P["n0"],
           de=P["de"],wci=P["wci"],B0=P["B0"])

    files=sorted(
        glob.glob(str(Path(args.phase_root)/"step*"/"diags"/"diag1*")),
        key=step_from_parent
    )
    if len(files)<4:
        raise RuntimeError(
            f"need at least four particle-rich phase plotfiles; found {len(files)}"
        )

    eh=np.loadtxt(args.em_history)
    if eh.ndim==1:
        eh=eh[None,:]
    # columns written by analyze_ishizawa_generalized_em_force.py
    ht=eh[:,1]
    hq=eh[:,4]
    hrequired=eh[:,-1]

    rows=[]
    labels=["expanded","contracting","contracted","expanding"]

    for k,fn in enumerate(files):
        step=step_from_parent(fn)
        M=load_mesh(fn,args.coarsen)
        ION=deposit_species(fn,"ions",p["mi"],M,p)
        ELE=deposit_species(fn,"electrons",p["me"],M,p)

        tci=P["wci"]*M["t"]
        q=float(np.interp(tci,ht,hq))
        areq=float(np.interp(tci,ht,hrequired))

        ni=np.abs(M["rho_i"])/QE
        ne=np.abs(M["rho_e"])/QE

        Pzz_i=p["mi"]*ni*ION["czz"]
        Pxz_i=p["mi"]*ni*ION["cxz"]
        Pzz_e=p["me"]*ne*ELE["czz"]
        Pxz_e=p["me"]*ne*ELE["cxz"]

        zmax=args.core_z_de*P["de"]
        QPi,jlo,jhi=rectangular_virial(Pzz_i,M["z"],M["dx"],M["dz"],zmax)
        QPe,_,_=rectangular_virial(Pzz_e,M["z"],M["dx"],M["dz"],zmax)

        QPi_direct=direct_pressure_force(
            Pxz_i,Pzz_i,M["x"],M["z"],M["dx"],M["dz"],jlo,jhi
        )
        QPe_direct=direct_pressure_force(
            Pxz_e,Pzz_e,M["x"],M["z"],M["dx"],M["dz"],jlo,jhi
        )

        rhoi=p["mi"]*ni
        rhoe=p["me"]*ne
        Tzz_i=rhoi*ION["uz"]**2
        Tzz_e=rhoe*ELE["uz"]**2
        QBi,_,_=rectangular_virial(Tzz_i,M["z"],M["dx"],M["dz"],zmax)
        QBe,_,_=rectangular_virial(Tzz_e,M["z"],M["dx"],M["dz"],zmax)

        Z=np.broadcast_to(M["z"][None,:],ni.shape)
        core=slice(jlo,jhi+1)
        inertia=float(np.sum((rhoi*Z*Z)[:,core])*M["dx"]*M["dz"])
        fac=1.0/(inertia*P["wci"]**2)

        api=QPi*fac
        ape=QPe*fac
        abulk_i=QBi*fac
        abulk_e=QBe*fac
        apart=api+ape+abulk_i+abulk_e

        label=labels[k] if k<len(labels) else f"phase{k}"
        rows.append([
            step,tci,q,areq,inertia,
            api,ape,api+ape,abulk_i,abulk_e,
            abulk_i+abulk_e,apart,
            QPi_direct*fac,QPe_direct*fac,
            ION["Nmacro"],ELE["Nmacro"]
        ])

        print(
            f"{label:11s} step={step} tci={tci:.4f} q={q:+.4f} "
            f"required={areq:+.3f} P_i={api:+.3f} P_e={ape:+.3f} "
            f"bulk={abulk_i+abulk_e:+.3f} particle={apart:+.3f}"
        )

    a=np.asarray(rows,float)
    order=np.argsort(a[:,1]); a=a[order]

    np.savetxt(
        "ishizawa_particle_pressure_phases.txt",a,
        header=(
            "step omega_ci_t q required_nonEM_acceleration inertia "
            "a_Pi_virial a_Pe_virial a_Ptotal_virial "
            "a_bulk_i_virial a_bulk_e_virial a_bulk_total_virial "
            "a_particle_stress_total a_Pi_direct a_Pe_direct "
            "Nmacro_i Nmacro_e"
        )
    )

    t=a[:,1]; q=a[:,2]; req=a[:,3]
    api=a[:,5]; ape=a[:,6]; apt=a[:,7]
    abulk=a[:,10]; apart=a[:,11]
    api_d=a[:,12]; ape_d=a[:,13]

    channels={
        "ion pressure":api,
        "electron pressure":ape,
        "total pressure":apt,
        "bulk stress":abulk,
        "particle stress total":apart,
    }
    stats={}
    for name,y in channels.items():
        slope,intercept,r2=linear_fit(q,y)
        corr=float(np.corrcoef(req,y)[0,1]) if len(y)>2 else np.nan
        stats[name]=(slope,intercept,r2,corr)

    fig,axs=plt.subplots(3,1,figsize=(9,9),sharex=True)
    axs[0].plot(t,req,"o-",lw=2,label="required non-EM residual")
    axs[0].plot(t,apt,"o-",label="ion+electron pressure")
    axs[0].plot(t,abulk,"o-",label="bulk momentum-flux stress")
    axs[0].plot(t,apart,"o-",lw=2,label="total particle stress")
    axs[0].axhline(0,lw=.7)
    axs[0].set_ylabel("generalized acceleration")
    axs[0].legend(fontsize=8)

    axs[1].plot(t,api,"o-",label="ion pressure")
    axs[1].plot(t,ape,"o-",label="electron pressure")
    axs[1].axhline(0,lw=.7)
    axs[1].set_ylabel("pressure contribution")
    axs[1].legend(fontsize=8)

    axs[2].plot(t,api_d,"o--",label="ion pressure direct divergence")
    axs[2].plot(t,api,"o-",label="ion pressure virial")
    axs[2].plot(t,ape_d,"s--",label="electron direct divergence")
    axs[2].plot(t,ape,"s-",label="electron virial")
    axs[2].axhline(0,lw=.7)
    axs[2].set_ylabel("direct / virial check")
    axs[2].set_xlabel(r"$\omega_{ci}t$")
    axs[2].legend(fontsize=8)
    for ax in axs: ax.grid(alpha=.25)
    fig.suptitle("Particle pressure/stress at four breathing phases")
    fig.tight_layout()
    fig.savefig("ishizawa_particle_pressure_phases.png",dpi=210)
    plt.close(fig)

    fig,ax=plt.subplots(figsize=(7,5.5))
    ax.scatter(q,req,s=65,label="required non-EM residual")
    for name,y in [
        ("ion pressure",api),("electron pressure",ape),
        ("total pressure",apt),("bulk stress",abulk),
        ("particle total",apart)
    ]:
        ax.plot(q,y,"o-",label=name)
    ax.axhline(0,lw=.7); ax.axvline(0,lw=.7)
    ax.set_xlabel("width displacement q")
    ax.set_ylabel("generalized acceleration")
    ax.grid(alpha=.25); ax.legend(fontsize=8)
    ax.set_title("Does particle stress supply the missing restoring channel?")
    fig.tight_layout()
    fig.savefig("ishizawa_particle_pressure_vs_q.png",dpi=210)
    plt.close(fig)

    with open("ishizawa_particle_pressure_phases_summary.txt","w") as f:
        f.write("Ishizawa-scale particle pressure/stress phase diagnostic\n")
        f.write("========================================================\n\n")
        f.write(f"particle-rich states = {len(a)}\n")
        f.write(f"coarsening factor = {args.coarsen}\n")
        f.write(f"core |z|/de <= {args.core_z_de:.6f}\n\n")
        f.write(
            "step  tci       q          required     a_Pi       a_Pe       "
            "a_Ptot     a_bulk     a_particle\n"
        )
        for r in a:
            f.write(
                f"{int(r[0]):6d} {r[1]:8.4f} {r[2]:+10.5f} "
                f"{r[3]:+11.5e} {r[5]:+11.5e} {r[6]:+11.5e} "
                f"{r[7]:+11.5e} {r[10]:+11.5e} {r[11]:+11.5e}\n"
            )

        f.write("\nFour-phase slope/correlation diagnostics\n")
        f.write("----------------------------------------\n")
        f.write("channel                  slope_vs_q       R2       corr_with_required\n")
        for name,(slope,intercept,r2,corr) in stats.items():
            f.write(f"{name:24s} {slope:+14.6e} {r2:9.5f} {corr:+12.6f}\n")

        rel_i=np.sqrt(np.mean((api_d-api)**2))/max(
            np.sqrt(np.mean(api**2)),1e-300
        )
        rel_e=np.sqrt(np.mean((ape_d-ape)**2))/max(
            np.sqrt(np.mean(ape**2)),1e-300
        )
        f.write("\nDirect-divergence vs virial consistency\n")
        f.write("---------------------------------------\n")
        f.write(f"ion relative RMS difference = {rel_i:.8e}\n")
        f.write(f"electron relative RMS difference = {rel_e:.8e}\n\n")
        f.write("Interpretation guide\n")
        f.write("--------------------\n")
        f.write(
            "The four points are a mechanism screen, not a final harmonic fit. "
            "A promising missing-restoring channel should vary with the same "
            "sign/phase as required_nonEM_acceleration and should have a "
            "negative slope versus q.  Agreement of the direct-divergence and "
            "virial pressure estimates is an important PIC-noise check.  If "
            "particle pressure/stress is promising, generate a denser set of "
            "particle-rich phases before quoting a kinetic stiffness or period.\n"
        )

    print("Saved ishizawa_particle_pressure_phases.txt")
    print("Saved ishizawa_particle_pressure_phases_summary.txt")
    print("Saved ishizawa_particle_pressure_phases.png")
    print("Saved ishizawa_particle_pressure_vs_q.png")


if __name__=="__main__":
    main()
